-- Bradley catalog: item modifiers (part 3 of 3). Run after 006 items.
-- IMPORTANT: select all (Ctrl+A) before Run — do not run a partial selection.

delete from public.catalog_item_modifiers
where part_number in (
  select part_number from public.catalog_items where vendor_name = 'Bradley Company, LLC'
);

insert into public.catalog_item_modifiers (
  catalog_item_id, part_number, modifier_sequence, modifier_code, modifier_type, app_use
)
select
  ci.id,
  src.part_number,
  src.modifier_sequence,
  src.modifier_code,
  src.modifier_type,
  src.app_use
from (
  values
    ('8120-001180', 1, 'MOUNT_CONCEALED', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8120-001180', 2, 'OD_1.5_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8120-001180', 3, 'LENGTH_18_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8120-001180', 4, 'DESIGN_CHANGE', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8120-001360', 1, 'MOUNT_CONCEALED', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8120-001360', 2, 'OD_1.5_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8120-001360', 3, 'LENGTH_36_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8120-001360', 4, 'DESIGN_CHANGE', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8120-001240', 1, 'MOUNT_CONCEALED', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8120-001240', 2, 'OD_1.5_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8120-001240', 3, 'LENGTH_24_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8120-001240', 4, 'DESIGN_CHANGE', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8120-001420', 1, 'MOUNT_CONCEALED', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8120-001420', 2, 'OD_1.5_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8120-001420', 3, 'LENGTH_42_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8120-001420', 4, 'DESIGN_CHANGE', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8122-001180', 1, 'TEXTURE_PEENED', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8122-001180', 2, 'MOUNT_CONCEALED', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8122-001180', 3, 'OD_1.5_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8122-001180', 4, 'LENGTH_18_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8122-001180', 5, 'DESIGN_CHANGE', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8122-001240', 1, 'TEXTURE_PEENED', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8122-001240', 2, 'MOUNT_CONCEALED', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8122-001240', 3, 'OD_1.5_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8122-001240', 4, 'LENGTH_24_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8122-001240', 5, 'DESIGN_CHANGE', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8122-001360', 1, 'TEXTURE_PEENED', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8122-001360', 2, 'MOUNT_CONCEALED', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8122-001360', 3, 'OD_1.5_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8122-001360', 4, 'LENGTH_36_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8122-001360', 5, 'DESIGN_CHANGE', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8122-001420', 1, 'TEXTURE_PEENED', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8122-001420', 2, 'MOUNT_CONCEALED', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8122-001420', 3, 'OD_1.5_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8122-001420', 4, 'LENGTH_42_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8122-001420', 5, 'DESIGN_CHANGE', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8320-001180', 1, 'MOUNT_CONCEALED', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8320-001180', 2, 'OD_1.25_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8320-001180', 3, 'LENGTH_18_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8320-001360', 1, 'MOUNT_CONCEALED', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8320-001360', 2, 'OD_1.25_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8320-001360', 3, 'LENGTH_36_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8320-001420', 1, 'MOUNT_CONCEALED', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8320-001420', 2, 'OD_1.25_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('8320-001420', 3, 'LENGTH_42_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('780-024360', 1, 'FRAME_ANGLE', 'frame', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('780-024360', 2, 'SIZE_24X36', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('780-018360', 1, 'FRAME_ANGLE', 'frame', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('780-018360', 2, 'SIZE_18X36', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('781-024360', 1, 'FRAME_CHANNEL', 'frame', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('781-024360', 2, 'SIZE_24X36', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('781-018360', 1, 'FRAME_CHANNEL', 'frame', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('781-018360', 2, 'SIZE_18X36', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('780-024480', 1, 'FRAME_ANGLE', 'frame', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('780-024480', 2, 'SIZE_24X48', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('781-024480', 1, 'FRAME_CHANNEL', 'frame', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('781-024480', 2, 'SIZE_24X48', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('5402-00000', 1, 'ACCESSORY_DISPENSER', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('5402-00000', 2, 'MOUNT_SURFACE', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('5402-00000', 3, 'CAPACITY_DUAL', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('4722-15000', 1, 'ACCESSORY_DISPOSAL', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('4722-15000', 2, 'MOUNT_SURFACE', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('4781-11000', 1, 'ACCESSORY_DISPOSAL', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('4781-11000', 2, 'MOUNT_SURFACE', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('250-15000', 1, 'MOUNT_SURFACE', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('747-024360', 1, 'FRAME_FRAMELESS', 'frame', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('747-024360', 2, 'SIZE_24X36', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('2494-00000', 1, 'AUTOMATIC', 'operation', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('234-11000', 1, 'MOUNT_SURFACE', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('234-11000', 2, 'WASTE_12_GAL', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('234-00000', 1, 'MOUNT_RECESSED', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('234-00000', 2, 'WASTE_12_GAL', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('234-10000', 1, 'MOUNT_SEMI_RECESSED', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('234-10000', 2, 'WASTE_12_GAL', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('6315-KT000', 1, 'SENSOR', 'operation', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('6563-00000', 1, 'MANUAL_PUSH', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('6563-00000', 2, 'CAPACITY_40_OZ', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('6563-00000', 3, 'MOUNT_PUSH_IN', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('6A03-11000', 1, 'AUTOMATIC', 'operation', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('6A03-11000', 2, 'CAPACITY_27_OZ', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('6542-00000', 1, 'MOUNT_WALL_MOUNT', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('5054-00000', 1, 'ACCESSORY_DISPENSER', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('5054-00000', 2, 'MOUNT_SURFACE', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('5054-00000', 3, 'CAPACITY_SINGLE', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('5224-00000', 1, 'ACCESSORY_DISPENSER', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('5224-00000', 2, 'MOUNT_SURFACE', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('5224-00000', 3, 'CAPACITY_DUAL', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('5425-00000', 1, 'ACCESSORY_DISPENSER', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('5425-00000', 2, 'MOUNT_SURFACE', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('5425-00000', 3, 'CAPACITY_DUAL', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('5831-00000', 1, 'ACCESSORY_SEAT_COVER', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('5831-00000', 2, 'MOUNT_SURFACE', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('583-00000', 1, 'ACCESSORY_SEAT_COVER', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('583-00000', 2, 'MOUNT_SURFACE', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('407-45000', 1, 'RECESSED_UNIT', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('407-45000', 2, 'COIN_VENDOR', 'operation', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('962-00000', 1, 'MOUNT_RECESSED', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('962-00000', 2, 'FINISH_STAINLESS', 'finish_material_color', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('962-00000', 3, 'HEAVY_OR_STRUCTURAL_ANCHORING', 'install_complexity', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('962-11000', 1, 'MOUNT_SURFACE', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('962-11000', 2, 'FINISH_STAINLESS', 'finish_material_color', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('962-11000', 3, 'HEAVY_OR_STRUCTURAL_ANCHORING', 'install_complexity', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('963-00000', 1, 'COLOR_SPECKLED', 'finish_material_color', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('963-00000', 2, 'HEAVY_OR_STRUCTURAL_ANCHORING', 'install_complexity', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9631-00000', 1, 'COLOR_GRAY', 'finish_material_color', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9631-00000', 2, 'HEAVY_OR_STRUCTURAL_ANCHORING', 'install_complexity', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9632-00000', 1, 'COLOR_CREAM', 'finish_material_color', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9632-00000', 2, 'HEAVY_OR_STRUCTURAL_ANCHORING', 'install_complexity', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9569-00000', 1, 'STRUCTURAL_ANCHORING', 'install_complexity', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9569-00000', 2, 'REVERSIBLE', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9569-00000', 3, 'MATERIAL_PHENOLIC', 'finish_material_color', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9533-60720', 1, 'VINYL_CURTAIN', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9533-42720', 1, 'VINYL_CURTAIN', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9537-48780', 1, 'VINYL_CURTAIN', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9537-60720', 1, 'VINYL_CURTAIN', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9531-04800', 1, 'ROD_INSTALL', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9531-04800', 2, 'LENGTH_48_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9531-04800', 3, 'OD_1.25_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9531-06000', 1, 'ROD_INSTALL', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9531-06000', 2, 'LENGTH_60_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9531-06000', 3, 'OD_1.25_IN', 'size', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9540-00000', 1, 'HOOKS', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9540-00000', 2, 'WITH_ROLLERS', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9536-00000', 1, 'HOOKS', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9536-00000', 2, 'SS_SPRING', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9054-24000', 1, 'SURFACE_MOUNT', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9054-24000', 2, 'FINISH_SATIN_SS', 'finish_material_color', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9114-00000', 1, 'SINGLE_HOOK', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9114-00000', 2, 'FINISH_SATIN_STAINLESS_STEEL', 'finish_material_color', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9124-00000', 1, 'DOUBLE_HOOK', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9124-00000', 2, 'FINISH_SATIN_STAINLESS_STEEL', 'finish_material_color', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('914-00000', 1, 'DOUBLE_HOOK', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('914-00000', 2, 'FINISH_CHROME_PLATED_BRASS', 'finish_material_color', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('915-00000', 1, 'FINISH_CHROME_PLATED', 'finish_material_color', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9933-00000', 1, 'UTILITY_SHELF', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9933-00000', 2, 'MOP_BROOM_HOLDER', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9934-00000', 1, 'UTILITY_SHELF', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9934-00000', 2, 'MOP_BROOM_HOLDER', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9943-00000', 1, 'SURFACE_MOUNT', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9943-00000', 2, 'FINISH_STAINLESS', 'finish_material_color', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9953-00000', 1, 'MOP_BROOM_HOLDER', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9953-00000', 2, 'FINISH_STAINLESS', 'finish_material_color', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9954-00000', 1, 'MOP_BROOM_HOLDER', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9954-00000', 2, 'FINISH_STAINLESS', 'finish_material_color', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9983-00000', 1, 'MOP_BROOM_HOLDER', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9983-00000', 2, 'FINISH_STAINLESS', 'finish_material_color', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9813-00000', 1, 'PASS_THRU', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9813-00000', 2, 'STAINLESS', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9813-00000', 3, 'VERIFY_ROUGH_OPENING', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9984-00000', 1, 'MOP_BROOM_HOLDER', 'general', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('9984-00000', 2, 'FINISH_STAINLESS', 'finish_material_color', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('175-10000', 1, 'MOUNT_SEMI_RECESSED', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('175-10000', 2, 'FINISH_STAINLESS', 'finish_material_color', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('175-00000', 1, 'MOUNT_RECESSED', 'mount', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.'),
    ('175-00000', 2, 'FINISH_STAINLESS', 'finish_material_color', 'Use to select/apply labor rule modifier; values are suggested and should be tuned after field history.')
) as src(part_number, modifier_sequence, modifier_code, modifier_type, app_use)
join public.catalog_items ci
  on ci.vendor_name = 'Bradley Company, LLC'
 and ci.part_number = src.part_number;
