-- Starter labor modifier catalog (factor 1.00 until tuned).
-- Regenerate: npm run import:bradley

insert into public.labor_modifiers (modifier_code, modifier_name, modifier_type, labor_factor, description)
values
  ('ACCESSORY_DISPENSER', 'Accessory Dispenser', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('ACCESSORY_DISPOSAL', 'Accessory Disposal', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('ACCESSORY_SEAT_COVER', 'Accessory Seat Cover', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('AUTOMATIC', 'Automatic', 'operation', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('CAPACITY_27_OZ', 'Capacity 27 Oz', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('CAPACITY_40_OZ', 'Capacity 40 Oz', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('CAPACITY_DUAL', 'Capacity Dual', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('CAPACITY_SINGLE', 'Capacity Single', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('COIN_VENDOR', 'Coin Vendor', 'operation', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('COLOR_CREAM', 'Color Cream', 'finish_material_color', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('COLOR_GRAY', 'Color Gray', 'finish_material_color', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('COLOR_SPECKLED', 'Color Speckled', 'finish_material_color', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('DESIGN_CHANGE', 'Design Change', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('DOUBLE_HOOK', 'Double Hook', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('FINISH_CHROME_PLATED', 'Finish Chrome Plated', 'finish_material_color', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('FINISH_CHROME_PLATED_BRASS', 'Finish Chrome Plated Brass', 'finish_material_color', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('FINISH_SATIN_SS', 'Finish Satin Ss', 'finish_material_color', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('FINISH_SATIN_STAINLESS_STEEL', 'Finish Satin Stainless Steel', 'finish_material_color', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('FINISH_STAINLESS', 'Finish Stainless', 'finish_material_color', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('FRAME_ANGLE', 'Frame Angle', 'frame', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('FRAME_CHANNEL', 'Frame Channel', 'frame', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('FRAME_FRAMELESS', 'Frame Frameless', 'frame', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('HEAVY_OR_STRUCTURAL_ANCHORING', 'Heavy Or Structural Anchoring', 'install_complexity', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('HOOKS', 'Hooks', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('LENGTH_18_IN', 'Length 18 In', 'size', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('LENGTH_24_IN', 'Length 24 In', 'size', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('LENGTH_36_IN', 'Length 36 In', 'size', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('LENGTH_42_IN', 'Length 42 In', 'size', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('LENGTH_48_IN', 'Length 48 In', 'size', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('LENGTH_60_IN', 'Length 60 In', 'size', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('MANUAL_PUSH', 'Manual Push', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('MATERIAL_PHENOLIC', 'Material Phenolic', 'finish_material_color', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('MOP_BROOM_HOLDER', 'Mop Broom Holder', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('MOUNT_CONCEALED', 'Mount Concealed', 'mount', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('MOUNT_PUSH_IN', 'Mount Push In', 'mount', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('MOUNT_RECESSED', 'Mount Recessed', 'mount', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('MOUNT_SEMI_RECESSED', 'Mount Semi Recessed', 'mount', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('MOUNT_SURFACE', 'Mount Surface', 'mount', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('MOUNT_WALL_MOUNT', 'Mount Wall Mount', 'mount', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('OD_1.25_IN', 'Od 1.25 In', 'size', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('OD_1.5_IN', 'Od 1.5 In', 'size', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('PASS_THRU', 'Pass Thru', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('RECESSED_UNIT', 'Recessed Unit', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('REVERSIBLE', 'Reversible', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('ROD_INSTALL', 'Rod Install', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('SENSOR', 'Sensor', 'operation', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('SINGLE_HOOK', 'Single Hook', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('SIZE_18X36', 'Size 18X36', 'size', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('SIZE_24X36', 'Size 24X36', 'size', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('SIZE_24X48', 'Size 24X48', 'size', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('SS_SPRING', 'Ss Spring', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('STAINLESS', 'Stainless', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('STRUCTURAL_ANCHORING', 'Structural Anchoring', 'install_complexity', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('SURFACE_MOUNT', 'Surface Mount', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('TEXTURE_PEENED', 'Texture Peened', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('UTILITY_SHELF', 'Utility Shelf', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('VERIFY_ROUGH_OPENING', 'Verify Rough Opening', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('VINYL_CURTAIN', 'Vinyl Curtain', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('WASTE_12_GAL', 'Waste 12 Gal', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.'),
  ('WITH_ROLLERS', 'With Rollers', 'general', 1.000, 'Starter factor 1.00 — tune in Labor Rules later.')
on conflict (modifier_code) do update set
  modifier_name = excluded.modifier_name,
  modifier_type = excluded.modifier_type,
  description = excluded.description;
